[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#cbd5e1"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
